// Drizzle schema for Neon Postgres: users / builds / quota / feedback (source of truth for drizzle-kit migrations).
import { boolean, date, index, integer, jsonb, pgTable, primaryKey, serial, text, timestamp } from 'drizzle-orm/pg-core'
import type { BuildSpec, BuildStatus } from './types'

// Data minimization (PRD §7): only the GitHub user id, login, and creation time.
export const users = pgTable('users', {
  id: text('id').primaryKey(), // GitHub user id
  githubLogin: text('github_login').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

export const builds = pgTable(
  'builds',
  {
    id: text('id').primaryKey(), // uuid generated by the adapter
    userId: text('user_id')
      .notNull()
      .references(() => users.id),
    status: text('status').$type<BuildStatus>().notNull(),
    spec: jsonb('spec').$type<BuildSpec>().notNull(),
    externalId: text('external_id'), // executor task id (e.g. workflow run)
    queuePosition: integer('queue_position'),
    logUrl: text('log_url'),
    artifactUrl: text('artifact_url'),
    artifactExpiresAt: timestamp('artifact_expires_at', { withTimezone: true }),
    failureReason: text('failure_reason'),
    quotaRefunded: boolean('quota_refunded').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index('idx_builds_user_id').on(table.userId), index('idx_builds_status').on(table.status)],
)

export const quota = pgTable(
  'quota',
  {
    userId: text('user_id')
      .notNull()
      .references(() => users.id),
    day: date('day', { mode: 'string' }).notNull(), // UTC day 'YYYY-MM-DD'
    used: integer('used').notNull().default(0),
  },
  (table) => [primaryKey({ columns: [table.userId, table.day] })],
)

export const feedback = pgTable('feedback', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull(),
  message: text('message').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})
